### ISSUE TITLE
Game crash : temp value revert to nil between "not nil" test and "temp < fire_temp" cooking peeled_anperla_tuber

### ISSUE THREAD

**Issue by zabka** [jeremyshannon/Exile#13]
Hello, 

Thank you for keeping this alive :)

I got this error while trying to bake peeled anperla tuber near a fire block on natural gravel (inside a cave)

AsyncErr: ServerThreead::run Lua Runtime error from mod 'tech' in callback node_on_timer(): ....4.1-win64\bin\..\games\exile\mods\tech/plant_crafts.lua:169:attempt to compare number with nil
stack traceback:
 ....4.1-win64\bin\..\games\exile\mods\tech/plant_crafts.lua:169: in function <....4.1-[...]/plant_crafts.lua:145>

Looking at the code, it seems "temp" revert to "nil" between the not nil test and the test with temp < fire_temp.
I know nothing about lua, but it looks like temp is updated by another thread between the 2 tests which trigger the error. I assume locking this portion of code would prevent this.

I retried multiple times: come back in the game, letting it run few seconds, planting new peeled anperla and causing new crashes.

Cheers

**Comment by jeremyshannon** [comment]
Huh. That should not be happening. I'll look into it.

**Comment by jeremyshannon** [comment]
Fixed by https://github.com/jeremyshannon/Exile/commit/e3088b36fb5b62e52643da3ad0ddb63acd218df8
