### ISSUE TITLE
Handling Suicide Appropriately

### ISSUE THREAD

**Issue by DokimiCU** [jeremyshannon/Exile#164]
A thought that comes out of #159 (controversial subjects), and something that's niggled at me for a while...

This might sound pedantic, but bear with me. This is a minor niggle, but it's a case of aiming for best practice on an extremely serious subject.

The _suicide chat command_ has bothered me for a while. I understand and agree with the purpose (respawn). However, we need to remember that the game will be played by people who are actively suicidal (indeed they may be playing it precisely to escape from that traumatic situation).

The player should only be presented with the concept of suicide when they actively want to end their character's life. Not just respawn 'coz I'm bored, but they are actually roleplaying taking their own life. The consequences there need to be true to reality - the attempt is often agonizing and often fails.

Currently the chat command presents the player with the option of suicide when they just want a new character or a different location. It makes suicide instant and painless. (on the plus side it makes it a brief moment, hence why this is minor issue. And I like the "You've come to your senses and decided to keep trying" line).

A possible improvement:
- replace suicide with a "Give up" command. Chat message "One day [Character name] disappeared and was never seen again..." (how they died is left ambiguous, not directly attributed to suicide).
- add a "New Character" command. Stops people from murdering themselves just because they don't like this character. Respawn them in the same location. Maybe limit it to 3 goes within 3 minutes of respawning (so no one spams it to get the "perfect" character).
- If the player really wants to die then they have to roleplay that horrid experience in the world e.g. by drowning, burning, falling etc. Suicide should never be an optimal strategy. The game ought to reward overcoming the urge to give up and die. 

Look up the "Werther Effect" and the "Papageno Effect" if you want to understand where I'm coming from on all this.

**Comment by Shadow8472** [comment]
There was one time before I learned about the suicide command that I really could have used it. I was newly spawned and trying to rest in a cave. My character got too tired to jump and subsequently got stuck, buried alive as I watched the energy drain. To my horror, I had to wait to die of dehydration/starvation while hopelessly lost in the dark.

Game mechanics wise, some sort of /stuck is important. You're right: /suicide should be handled with more care than "You give into your fate." At the very least, a crude survivability check should be performed based on HUD stats and items you have on that might help. 

Here is my take on a /suicide system that tries to be more sensitive, but still allows it.

First time:
- You think about ending it all, but <town's folk member> <encouragement> (but the look the mean, old lady shot you motivates you to prove her wrong) (but the kindly town begger wouldn't want you to give up).
- Your sentence was technically already carried out the moment they sent you here. No use throwing the rest of your life away.
 
All stats above 50%:
- You consider your fate. You still have so much to live for.
- What would your <family member> say if he/she learned you did that?

Energy below 50%:
- Things are bad, but you still have time to pick a spot to weave <best clothes item> out of <fiber plant> and find a place to rest.
- Things may look bad, but a little sleep in a cave or cuddled next to a tree will do you wonders.

Water below 50%:
- Your throat's a bit dry, but you have some juicy <water-bearing plant/fruit> you can munch on.
- Your throat's a bit dry, but you can still <dig seepage pit> in one of the river beds around.

Hunger below 50%:
- Your belly's empty, but you still have some <food> to eat.

Survival not likely, state resets after 60 seconds.
- (first try): You seriously consider your fate.
- (repeated tries faster than 10 seconds, go back to first try afterwords): No, not worth it.
- (second try): (dialogue box to break immersion) Are you sure you need to respawn?

**Comment by Izzyb1234** [comment]
Thanks DokimiCU.  I really appreciate your insight on this.

I too had some concern about naming the command /suicide.  It's a difficult subject for a lot of people, myself included.  I provided aliases of /killme and /respawn for those uncomfortable with the command, and initially made the message a joke about slipping on a banana to bring some levity to a serious matter.  I hadn't considered the impact it may have on a player that was suicidal though.  

I appreciate the thought you and Shadow8472  have put into this and agree it can be handled better.  I was looking at the game mechanic aspect of needing a way to restart when you know you're done for.  Being stuck in a dark place with nothing you can dig and no way out is exactly the situation I built the command for.  /restart or /respawn that doesn't leave bones or mention the "death" of the previous player would accomplish that goal.  I'll send a PR with that as a fix for now.

Part of the reason I had the command send a chat message was so other players would know and could offer help to a player struggling in the game.  Perhaps we can make /suicide a request for help that provides tips as shadow suggested and ask if they want help.  If they say yes, then send a chat message.  If they say no, tell them about the /restart command.

**Comment by Crystalwarrior** [comment]
> replace suicide with a "Give up" command. Chat message "One day [Character name] disappeared and was never seen again..." (how they died is left ambiguous, not directly attributed to suicide).

I like this option the most, and keeping the delay of /suicide action. Suicide can remain an alias but the messages could leave the character's fate ambiguous

**Comment by DokimiCU** [comment]
Looking back at this, my suggested chat message ("disappeared...") isn't appropriate either. This still feeds into the suicidal thinking that it's possible to just disappear.

Seeing as this message was intended as a multiplayer "Assist this player" signal maybe: "[Player name] got stuck and gave up" would communicate that better.

**Comment by Izzyb1234** [comment]
I'll have a look at fixing this today.  I'll rename it /restart with alias /respawn.  And have it kill the player but not leave bones or a message.  I'll have it suggest asking for help in global chat and refer people to the wiki for tips.  Maybe I'll start a wiki page with tips for new players.

**Comment by Crystalwarrior** [comment]
Wait not leaving behind bones is all sorts of bad. It means you'll permanently lose your stuff with no way to re acquire it, or is otherwise an easy escape out of any pve or pvp situation. Are you sure about this?

**Comment by jeremyshannon** [comment]
It still requires a confirmation. so It's slower than just logging out, and yes, you do lose your inventory. Logging out is a better escape option all around, and there's not a lot I can do about that one.
 Allowing admins to retrieve items from a restart is on the drawing board in order to handle the corner case where somebody loses something they wanted to keep due to ignorance of what restart will do, or where someone's carrying another player's stuff (on purpose or accidentally) when they call this.

**Comment by Izzyb1234** [comment]
I forgot to update the prompt to warn about loosing all your stuff.  I'll add it in with the pr to create an inventory recovery process for admins.  It was intended as a solution to a bad start where you get stuck in a hole with no way out - not as an easy way out of a situation you should be able to resolve another way.  You always have the option to kill your player in a way that will leave bones behind.  Standing on a torch will do it.
