### ISSUE TITLE
Dressing in Layers (bug report/feature request)

### ISSUE THREAD

**Issue by Shadow8472** [jeremyshannon/Exile#165]
Dressing in layers can be accomplished by replacing a piece of clothing and putting it straight to another clothing spot.
![Screenshot_20220715_005414](https://user-images.githubusercontent.com/53035941/179195415-830d0b94-4ef7-4526-b5fb-fe7b26a31ca3.png)

(Totally didn't mean to completely take over bug report with clothing overhaul proposal) Personally, I like the ability to dress in layers, but restrictions should apply:
- Limit 1 each woven (except blankets)
- Limit 1 hat.
- Limit 1 cape (or cloak).
- Limit 1 light pants + 1 heavy pants (sweat pants)
- Limit 3 blankets

Shirts:
Shirts are traditionally more versatile.
- Light is below heavy is below poncho.
- Two or more heavy shirts limit mobility.
- Heavy shirt can be worn as a sweater.

So, in my mind, a reasonable loadout for cold may be: heavy hat, light shirt, heavy shirt, light pants, heavy pants, cape/cloak. Underground heat also bothers me in that while light shirts and shorts may help regulate body temperature, I'm not so sure the same applies for hats or capes.

**Comment by jeremyshannon** [comment]
Fixed by 3456b4d8
