### ISSUE TITLE
Stone spears dig have cracky digging caps to high; can dig at least limestone and ironstone

### ISSUE THREAD

**Issue by wizardofgcc** [jeremyshannon/Exile#169]
Checked in updated version on singleplayer and LoC. Stone spears can dig limestone and ironstone (not checked on granite, jade or gneiss). Definetely seems like they should not be able to do that, as a tool you can get on day 1.

**Comment by jeremyshannon** [comment]
Wow, I did not even think to check the digging properties on a weapon mod. That makes no sense, spears are terrible digging tools!
