### ISSUE TITLE
Mushroom: duration nil value

### ISSUE THREAD

**Issue by sirken** [jeremyshannon/Exile#30]
Getting an underground mushroom-related crash. Doesn't look like 'duration' is defined previously. Log:

> 2021-09-26 19:25:21: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'nodes_nature' in callback node_on_timer(): ...netest/bin/../games/Exile/mods/nodes_nature/life.lua:138: attempt to perform arithmetic on global 'duration' (a nil value)
> 2021-09-26 19:25:21: ERROR[Main]: stack traceback:
> 2021-09-26 19:25:21: ERROR[Main]: 	...netest/bin/../games/Exile/mods/nodes_nature/life.lua:138: in function 'grow_seed'
> 2021-09-26 19:25:21: ERROR[Main]: 	...netest/bin/../games/Exile/mods/nodes_nature/life.lua:368: in function <...netest/bin/../games/Exile/mods/nodes_nature/life.lua:361>

https://github.com/jeremyshannon/Exile/blob/3076d479d8f224e23725ffe2d6d5bde47fe80ba8/mods/nodes_nature/life.lua#L135-L138

**Comment by jeremyshannon** [comment]
Aww man, that should be "elapsed." This is why self-merging is terrible.
