### ISSUE TITLE
Lua crash when baking peeled anperla tuber

### ISSUE THREAD

**Issue by wizardofgcc** [jeremyshannon/Exile#31]
> 2021-09-28 15:52:52: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'tech' in callback node_on_timer(): ... Support/minetest/games/exile/mods/tech/plant_crafts.lua:167: attempt to compare number with nil
2021-09-28 15:52:52: ERROR[Main]: stack traceback:
2021-09-28 15:52:52: ERROR[Main]: 	... Support/minetest/games/exile/mods/tech/plant_crafts.lua:167: in function <... Support/minetest/games/exile/mods/tech/plant_crafts.lua:145>

The reason for this crash seems to be that there is a wrong number of arguments when calling "bake_bread" in the timer function:

> minetest.register_node("tech:anperla_tuber_peeled", {
	description = "Peeled Anperla Tuber",
	...
  on_timer = function(pos, elapsed)
    --self, finished product, length, heat
    return bake_bread(pos, "tech:anperla_tuber_peeled", "tech:anperla_tuber_cooked", 7, 100) 
  end,
})

Should be:

> minetest.register_node("tech:anperla_tuber_peeled", {
	description = "Peeled Anperla Tuber",
	...
  on_timer = function(pos, elapsed)
    --self, finished product, length, heat
    return bake_bread(pos, "tech:anperla_tuber_peeled", "tech:anperla_tuber_cooked", "tech:anperla_tuber_burned" 7, 100) 
  end,

Although needs to be a definition for burned anperla tubers

**Comment by jeremyshannon** [comment]
That one's been lurking since burned food was added. I guess I never bake single tubers rather than mashing them up. For a quick fix, I've just made the old "burn away to nothing" behavior happens if the burned_name is nil.
