### ISSUE TITLE
climate.heat_transfer() only checks nodes below, prevents horizontal heat transfer between heatable nodes

### ISSUE THREAD

**Issue by mel-odious** [jeremyshannon/Exile#38]
While digging through heat transfer stuff I noticed that mods/climate/temperature.lua:381 in climate.heat_transfer() causes heatable nodes to only check the y-coords below them for heat transfer, preventing heat exchange between nodes of the same height.  This leads to odd behaviour like a 2-deep, 1-high kiln not heating the rear nodes at all (too far away for the fire to heat via climate.air_temp_source()) whereas a 2-deep, 2-high kiln can heat the rear ones due to having heatable nodes on different y-coords.

Changing the `-` to a `+` on that line so it checks a 3x3x3 area matches the logic in climate.air_temp_source() and makes both kilns behave the same so it seems to be a typo.

**Comment by jeremyshannon** [comment]
Yep, that is a typo! Fixing.
