### ISSUE TITLE
Beds don't always clear their markers

### ISSUE THREAD

**Issue by jeremyshannon** [jeremyshannon/Exile#44]
Under some circumstances (lag?) a bed's marker will remain after a player gets up, and if the player lays down again he can claim multiple beds.
 The code needs to prevent claiming more than one bed, but it's also supposed to remove the marker as soon as you get up.

 On a related note, markers should be able to time out and get removed after a configurable delay, perhaps 7 IRL days, lest multiplayer servers get filled with lingering beds of long-gone players. Admins can still remove the beds with protection_bypass privs, but it might be nice to let server owners set up the markers to be taken off automatically.

**Comment by jeremyshannon** [comment]
Oh and if the marker times out, I'd like to move the bed to player inventory if possible, but that may be tricky since player inv is inaccessible when not logged in. Check on logout, set a bed_rest key, "can_accept_bed = { player1, player2, ... }"

**Comment by DanS-User** [comment]
I removed my bed while on LoC server, which was laggy and ended up with the bed in my inventory, but at the same time half of the bed was still on the ground. The voxel is not clickable, removable or build or place a bed on it

**Comment by jeremyshannon** [comment]
That's a different bug which I thought had an issue already, but I see now that it doesn't.
 I do have a workaround in place for that particular bug, with a bed_clear LBM. When enabled, it removes lone half-beds whenever an area gets loaded, unless there's another bed right next to it. (In which case it can't be 100% certain which top belongs to which bottom and leaves it alone just to be safe)
 But that it happened when removing the bed under lag may help me fix that bug properly. Thanks!

**Comment by Izzyb1234** [comment]
Think this but was fixed?

**Comment by jeremyshannon** [comment]
I haven't seen any evidence of this in ages, so yes, it seems to have been resolved.

**Comment by jeremyshannon** [comment]
The bed clear ABM has been turned off for quite a while now on LoC, I'm probably going to remove it as I believe the bug (in the beds mod) is fixed. I sent the fix up to MTG, where it's kinda sitting stalled. (To be fair, there's more than one way to fix it.)
