### ISSUE TITLE
Player glitches and slides when hurt

### ISSUE THREAD

**Issue by jeremyshannon** [jeremyshannon/Exile#5]
Reports have come up that players sometimes end up sliding uncontrollably when hurt:
https://forum.minetest.net/viewtopic.php?p=392695#p392695
Testing would probably involve nerfing the spider's damage to a low, non-zero value and letting one whale on the player until the glitch happens.

This might be related to the standing-in-bed bug, which seems to be fixed by runs' player api.

**Comment by jeremyshannon** [comment]
This may be fixed now, but I never got it to happen for me in the first place, so I can't be sure.

**Comment by MisterE123** [comment]
On Land of Catastrophe server, it happens whenever I am almost out of life.
However, It seems reasonable... I no longer have the strength to walk another step

**Comment by jeremyshannon** [comment]
Yeah, that might be what it is, a combo of being crippled along with knockback, which would appear to be by design. The original report was a bit vague.
 Closing this unless somebody else comes forward with more info, because as is, I can't see anything worth doing here.
