### ISSUE TITLE
Updated peeled anperla tubers have problems

### ISSUE THREAD

**Issue by wizardofgcc** [jeremyshannon/Exile#57]
1. When a peeled anperla tuber before the name change is placed, it crashes the server, though the tuber is converted after the restart
2. Pre-change peeled anperla cannot be eaten, generate a "This item is not edible" message

**Comment by jeremyshannon** [comment]
Of course it was fine while I was on poking around, it waited until after I fell asleep to start crashing all night. The crash should be handled by b555320 -- an oversight in the bake code. It worked fine if you just pick up a food after it's cooked and eat it, but if you pick up a cooked food and put it down in-world again, it would try to read the cooked name from the bake table, which caused the crash.

**Comment by jeremyshannon** [comment]
And that should fix the "this is inedible" problem. The alias doesn't seem to take effect on player inventories, you have to put the aliased item down and pick it up to take effect. Minetest quirk, I guess.
 Now the eat function will check for aliases for old cooked food.
