### ISSUE TITLE
Moisture Evaporations

### ISSUE THREAD

**Issue by DanS-User** [jeremyshannon/Exile#8]
Hi, in mods/nodes_nature/moisture_spread.lua
at line 48
the game is deleting the node instead of changing
it from wet to dry.
I noticed tiles in my garden are disappearing

**Comment by jeremyshannon** [comment]
Was it tilled soil? Tilled soil can erode if there's a water node nearby or it's exposed on the sides. This could probably be indicated better to players, but I haven't decided how to go about that.

**Comment by DanS-User** [comment]
Yes, it was tilled soil and those tiles that were gone had an exposed side and a young plant on them. Thank you for letting me know what was the cause. 
Just to put it to definite rest, what "line 48" in moisture_spread.lua does? 
Thank you :)

**Comment by jeremyshannon** [comment]
It handles evaporation of water nodes. You can see that it's tied directly to the "Water Evaporate" abm directly below it, which is run on group:water.
 climate.can_evaporate checks that the water has an air tile above it, and it's not currently raining. If those are true, then the water has a chance to evaporate depending on temperature. 
 Wet soil is handled down below, in moisture_spread starting on line 213.

**Comment by DanS-User** [comment]
Thank you very much, it makes sense now.
Have a great day :)
