### ISSUE TITLE
granite Brick with Mortar cant be cracked

### ISSUE THREAD

**Issue by crodar33** [jeremyshannon/Exile#83]
We have list of block with mortar that can't be cracked by iron pickaxe.
bricks_and_mortar.lua
```
local list = {
	{"limestone", "Limestone", 3},
	{"ironstone", "Ironstone", 3},
  {"granite", "Granite", 1},
	{"basalt", "Basalt", 2},
	{"gneiss", "Gneiss", 1},
	{"jade", "Jade", 1},

}
```
All values except 2 and 3 can't be cracked ... it look like value 1 shall be most soft but the fact it doesn't work. I didn't understand how work configuration of iron pickaxe so I can't create correct PR. 
So it require to be fixed by fix material value or pickaxe settings.

**Comment by jeremyshannon** [comment]
Hardness is divided into three classes, with the first class material being the hardest. Iron can only remove second class material in Exile, the first requires artifact tools.
 This is all Dokimi's design, I'll have to think about whether or not to change it. In multiplayer, having materials that can't be dug easily makes theft and griefing much less attractive.
