### ISSUE TITLE
Make Antiquorium ladders solid, extendable

### ISSUE THREAD

**Issue by jeremyshannon** [jeremyshannon/Exile#96]
Antiq ladders are currently a bit unwieldy to use. It's possible to walk through them and fall off, they need a narrow collision box to prevent that.
 In addition, they should leverage the code from wooden ladders that allows you to right click on a ladder to build another on top of it, though AQ can build both ways and should probably try to build up first, and then try building down by one if there's a non-empty node above.

**Comment by Izzyb1234** [comment]
I think this issue is closed now.

**Comment by jeremyshannon** [comment]
Yeah, they extend, and leaving them non-solid is a reasonable compromise since you can only technically grab onto one side right now.
