### ISSUE TITLE
Needed: A heat overlay to complement the frost overlay

### ISSUE THREAD

**Issue by jeremyshannon** [jeremyshannon/Exile#98]
We currently have code to visually alert the player of dangerously cold temperatures by applying a frost overlay around the edges of his screen, but dangerously hot temperatures have no indicator as yet.
 I could find no overlay under a suitable license that would adequately represent heat. A heat haze effect would be best, but would likely require shaders; barring that, perhaps a wet screen around the edges to represent sweating would get the desired idea across.

**Comment by jeremyshannon** [comment]
I was already thinking of using a white haze overlay when you're standing in light, to indicate the effects of photosensitivity.
 There's not really an ideal choice for heat that I can see, apart from the one that requires shaders.

**Comment by DokimiCU** [comment]
I had a go at this (I find the art stuff pretty easy):

[https://github.com/DokimiCU/exile_experiments/tree/master/hud_overlays](url)
- lens flare effect for photosensitive (it even feels painful!)
- white haze for heat (good enough?)

**Comment by jeremyshannon** [comment]
Alright, adding the heat overlay is trivial, so that's done. The photosensitivity one will take some reshuffling of code to get it working, as there's presently no way to send that info up to the hud, I'll have to think about what to move where before I can insert it in a clean and future-proof way.
